language: node_js
node_js:
    - "10"
env:
    - CXX=g++-4.8
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
install:
    - npm install -g vuepress
script:
    - npm run docs:build
cache:
    directories:
        - "node_modules"
notifications:
    email: false
deploy:
    - provider: npm
        email: mailtojerry@foxmail.com
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
    - provider: pages
        skip-cleanup: true
        local_dir: docs/.vuepress/dist
        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep-history: true
        target-branch: gh-pages
        on:
            branch: master

branches:
  only:
    - master
script: echo "npm test temporarily disabled"
