language: node_js
node_js:
  - 11
os: linux
branches:
  only:
    - master
deploy:
  provider: npm
  email: mailtojerry@foxmail.com
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
script: echo "npm test temporarily disabled"
